### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by irfanismaya20** [stackbuilders/react-native-spotlight-tour#43]
I try install using npm but error,  i use react-native last version

**Comment by JoseLion** [comment]
@irfanismaya20 I'm sorry to hear you're having this issue. I tried using NPM v7, and it installs ok using the `--legacy-peer-deps` option. To avoid `--legacy-peer-deps` I think we'll need to update our dependencies and investigate further.

We use `styled-components` which has a peer dependency on `react-dom` (which should probably be optional 🤔). Since we don't specify a version for `react-dom`, it's using the latest and causing a conflict on the dependency tree.

However, if your issue is not related to the dependency tree resolution, can you please provide more details? (error trace, NPM version, Node version, and OS)

Thanks! 🙂

**Comment by irfanismaya20** [comment]
@JoseLion Thank you for answer 🙏. finally i try use yarn for install and working. I want to ask, how to call action "start" 
without i press button for show spotlight-tour? i try call "start" in useEffect (react hooks) but not show. Thank You

**Comment by JoseLion** [comment]
@irfanismaya20 yep, Yarn is another good option 🙂 glad to hear you solved it.

If you want to call `start()` imperatively I'd suggest using the reference to access the Tour methods. Then you can call it from within a useEffect for instance:
```tsx
function MyComponent(): React.ReactElement {
  const tourRef = useRef<SpotlightTour>(null);

  useEffect(() => {
    tourRef.current.start();
  }, [tourRef.current]);

  return (
    <SpotlightTourProvider ref={tourRef} steps={...}>
      {/* Your component goes here */}
    </SpotlightTourProvider>
  );
}
```

However, this is not ideal because we should try to avoid imperative code in React. So the same thing can be achieved with the `useSpotlightTour()` hook if you rearrange the component a bit:
```tsx
function MyComponent(): React.ReactElement {
  const { start } = useSpotlightTour();

  useEffect(() => {
    start();
  }, [start]);

  return (
    <>
      {/* Your component goes here */}
    </>
  );
};

function MyWrapper(): React.ReactElement {
  return (
    <SpotlightTourProvider steps={...}>
      <MyComponent />
    </SpotlightTourProvider>
  );
};
```

I hope this helps. Happy coding 🙂

**Comment by irfanismaya20** [comment]
@JoseLion Thank you for solution 🙏
